package no.ks.fiks.dokumentlager.klient.model.eksponertfor;

public enum EksponertForOrgType {
    ORGANISASJON, ORGANISASJON_BYGGESAKER, ORGANISASJON_FAKTURA, ORGANISASJON_POST,ORGANISASJON_SKJEMA, ORGANISASJON_ANDRESAKER
}
