package no.ks.fiks.dokumentlager.klient.model.eksponertfor;

enum EksponertForType {
    PERSON, ORGANISASJON, ORGANISASJON_BYGGESAKER, ORGANISASJON_FAKTURA, ORGANISASJON_POST,ORGANISASJON_SKJEMA, ORGANISASJON_ANDRESAKER, INTEGRASJON, AUTORISASJON, MATRIKKELENHET
}
